#' Build a Composite Structural Model from Link Paths
#'
#' Combines one or more sets of `link` paths into a unified structural model.
#' Each input must be a data frame generated by the `link()` function,
#' specifying directed associations between variables. The function merges these
#' links, identifies the outcome variable(s), and computes a valid topological
#' ordering. The model is assumed to be a directed acyclic graph.
#'
#' @param ... One or more `link` path objects created by the `link()` function.
#'   Each must be a data frame with columns `from` and `to`, representing
#'   directed edges in the model.
#'
#' @return A list with three components:
#' \describe{
#'   \item{\code{paths}}{A data frame of all combined directed edges.}
#'   \item{\code{outcomes}}{A character vector of terminal outcome node(s) (i.e., nodes with no outgoing edges).}
#'   \item{\code{order}}{A character vector of all nodes sorted in topological order, from predictors to outcomes.}
#' }
#'
#' @examples
#' # Define composite structure
#' composite_list <- composite_list(
#'   extraversion          = sprintf("e%01d", seq(10)),
#'   neuroticism           = sprintf("n%01d", seq(10)),
#'   agreeableness         = sprintf("a%01d", seq(10)),
#'   conscientiousness     = sprintf("c%01d", seq(10)),
#'   openness              = sprintf("o%01d", seq(10)),
#'   consistency_interest  = sprintf("gs%01d", c(2,3,5,7,8,11)),
#'   perseverance_effort   = sprintf("gs%01d", c(1,4,6,9,10,12)),
#'   grit                  = c("consistency_interest", "perseverance_effort")
#' )
#'
#' # Define model structure
#' composite_model <- composite_model(
#'   link(
#'     from = c("extraversion",
#'              "neuroticism",
#'              "agreeableness",
#'              "conscientiousness",
#'              "openness"),
#'     to = c("grit")
#'   )
#' )
#'
#' @export
composite_model <- function(...) {
  
  inputs <- list(...)
  
  # Collapse all path links
  paths <- purrr::reduce(inputs, rbind)
  
  
  # Identify the outcome variable
  outcomes <- setdiff(
    paths$to,
    paths$from
  )
  
  if (length(outcomes) == 0) {
    stop("Model has at least one cycle; cannot identify unique outcome(s).")
  }
  
  
  # Sort the order
  order <- rev(topo_sort_df(paths))
  
  # Put into list
  list(
    paths = paths,
    outcomes = outcomes,
    order = order
  )
  
}